on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: The env to pin
        options:
          - staging
          - prod

name: Pin env

jobs:
  copy-files:
    runs-on:
      - ubuntu-latest
    permissions:
      # needed for us to write back to the repo
      contents: write
    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          ssh-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}
          fetch-depth: 1
          persist-credentials: true

      - name: deploy-env
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Run deployment script
        run: |
          go run ./cmd/promote-build --env ${{ inputs.environment }}
      