on:
    repository_dispatch:
        types: [dependency_update]
    workflow_dispatch:

name: Webhook in lieu of cron test

jobs:
    print-time:
        runs-on:
            - ubuntu-latest
        if: ${{ github.event.client_payload.env == 'dogfood_us1' }} 
        steps:
         - name: pin-service
           shell: bash
           run: |
            echo ${{github.event.client_payload.env}}
            current_date_time=$( date "+%H:%M:%S" )
            echo $current_date_time;