on:
    repository_dispatch:
        types: [dependency_update]

name: Webhook in lieu of cron test

jobs:
    print-time:
        runs-on:
            - ubuntu-latest
        steps:
         - name: pin-service
           shell: bash
           run: |
            current_date_time=$( date "+%H:%M:%S" )
            echo $current_date_time;