name: Dynamic generation

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
jobs:
  get-service-list:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}
      - name: checkout code
        uses: actions/checkout@v3
        with:
            ref: 'main'
            ssh-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}
            fetch-depth: 1
            persist-credentials: true
      - name: Get All Images On ECR
        run: |
            # cycle though just directories
            cd argo-kubernetes-charts
            for dir in */ ; do
                if [ -d "$dir" ]; then
                # we use dir%/ to remove the trailing slash
                echo $dir
                echo "wtf github"
                output+="- ${dir%/}\n            "
            fi
            done
            sed "s/\$SERVICE_LIST/$output/g" "$GITHUB_WORKSPACE/.github/workflows/dynamic.template.yml" > "$GITHUB_WORKSPACE/.github/workflows/dynamic.yml"
            cat $GITHUB_WORKSPACE/.github/workflows/dynamic.yml

            git config --global user.email "deploys@blah.io" # this email may or may not exist
            git config --global user.name "Deploy Github Action"
            git add -A
            git commit -m "Changes found, adding a new service"
            git push origin main