on:
  workflow_dispatch:
    inputs:
      build_id:
        type: string
        required: true
        description: Build id to pin to
      environment:
        type: choice
        required: true
        description: The env to pin
        options:
          - staging
          - prod

name: Pin env

jobs:
  copy-files:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 1
          persist-credentials: true

      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}
  pin-service:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Pin it
        run: |
          mkdir -p state/${{ inputs.environment }}
          echo 'release: "${{ inputs.build_id }}"' > state/${{ inputs.environment }}/version.yml
          touch state/${{ inputs.environment }}/pinned
          git add -A
          git commit -m "Pinning ${{ inputs.build_id }} for ${{inputs.environment }}"
          git push origin main
      
      # - name: Commit + push
      #   uses: EndBug/add-and-commit@v9.1.4
      #   with:
      #     add: 'state'
      #     default_author: "github_actions"