on:
  workflow_dispatch:
    inputs:
      build_id:
        type: string
        required: true
        description: Build id to pin to
      environment:
        type: choice
        required: true
        description: The env to pin
        options:
          - prestaging_us1

name: Pin env

jobs:
  copy-files:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          ssh-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}
          fetch-depth: 1
          persist-credentials: true

      - name: pin-service
        shell: bash
        run: |
          CIRCLE_BUILD_NUMBER=123456
          
          #go run ./cmd/pin-environment --env ${{ inputs.environment }} --buildId ${{ inputs.build_id }} --buildNum $CIRCLE_BUILD_NUMBER

          if [[ ${{ inputs.environment }} =~ "pres" ]]; then
            ENVIRONMENT_GROUP="prestaging"
          elif [[ ${{ inputs.environment }} =~ "staging" ]]; then
            ENVIRONMENT_GROUP="staging"
          elif [[ ${{ inputs.environment }} =~ "production" ]]; then
            ENVIRONMENT_GROUP="production"
          else
            echo "${{ inputs.environment }} is not a valid service"
            exit 1;
          fi

          # cycle though just directories
          for dir in */ ; do
            if [ -d "$dir" ]; then
            # we use dir%/ to remove the trailing slash
            cat > argo-kubernetes-charts/${dir%/}/environment_values/$ENVIRONMENT_GROUP/${{ inputs.environment }}_${dir%/}_values.yaml <<EOL
            # THIS FILE IS MACHINE WRITTEN DO NOT EDIT
            release_id: "${{ inputs.build_id }}"
            global:
              release_id: "${{ inputs.build_id}}"
              infra_build_num: "${CIRCLE_BUILD_NUMBER}"
          EOL
            fi
            done

          # cat > argo-kubernetes-charts/${{ inputs.service }}/environment_values/$ENVIRONMENT_GROUP/${{ inputs.environment }}_${{ inputs.service }}_values.yaml <<EOL

          cat > argo-kubernetes-charts/${{ inputs.environment }}_${{ inputs.service }}_values.yaml <<EOL
          # THIS FILE IS MACHINE WRITTEN DO NOT EDIT
          release_id: "${{ inputs.build_id }}"
          global:
            release_id: "${{ inputs.build_id}}"
            infra_build_num: "${CIRCLE_BUILD_NUMBER}"
          EOL

          touch argo-kubernetes-charts/${{ inputs.environment }}_pinned
          
          git config --global user.email "deploys@blah.io" # this email may or may not exist
          git config --global user.name "Deploy Github Action"
          git add -A
          git commit -m "Pinning ${{ inputs.build_id }} for ${{ inputs.environment }}"
          git push origin main