on:
  workflow_dispatch:
    inputs:
      build_id:
        type: string
        required: true
        description: Build id to pin to
      environment:
        type: choice
        required: true
        description: The env to pin
        options:
          - staging

name: Pin env

jobs:
  copy-files:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          ssh-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}
          fetch-depth: 1
          persist-credentials: true

      - name: pin-service
        shell: bash
        run: |
          CIRCLE_BUILD_NUMBER=123456
          mkdir -p state/${{ inputs.environment }}
          
          go run ./cmd/pin-environment --env ${{ inputs.environment }} --buildId ${{ inputs.build_id }} --buildNum $CIRCLE_BUILD_NUMBER

          touch argo-kubernetes-charts/${{ inputs.environment }}_pinned
          git config --global user.email "deploys@blah.io" # this email may or may not exist
          git config --global user.name "Deploy Github Action"
          git add -A
          git commit -m "Pinning ${{ inputs.build_id }} for ${{ inputs.environment }}"
          git push origin main