on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          required: false
          description: The env to pin
          options:
            - staging
            - prod

name: Secrets test

jobs:
    copy-files:
        runs-on:
            - ubuntu-latest
        steps:
          - name: Install SSH Client
            uses: webfactory/ssh-agent@v0.9.0
            with:
                ssh-private-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}

          - name: Checkout
            uses: actions/checkout@v4
            with:
                ref: 'main'
                ssh-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}
                fetch-depth: 1
                persist-credentials: true

          - name: deploy-env
            uses: actions/setup-go@v5
            with:
                go-version: 'stable'
          - name: Run deployment script
            env: 
                fakeSecret: ${{ secrets.FAKE_SECRET }}
            run: |
                go run ./cmd/call-url
        