on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          required: true
          description: The environment to unpin in
          options:
            - staging
  
name: Unpin Environment

jobs:
    unpin-environment:
        runs-on:
            - ubuntu-latest
        steps:
            - name: Install SSH Client
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }} # this is a deploy key with write access to this (infra) repo saved in the repo secret variables

            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: 'main'
                ssh-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}
                fetch-depth: 1
                persist-credentials: true

            - name: Unpin environment
              shell: bash
              run: |
                PIN_FILE="state/${{ inputs.environment }}/argo/pinned"
                if [ -f $PIN_FILE ]; then
                    rm $PIN_FILE
                else
                    echo "No pin file to remove from state/${{ inputs.environment }}/argo"
                fi

                # ship it
                git config --global user.email "deploys@blah.io" # this email may or may not exist
                git config --global user.name "Deploy Github Action"
                git add -A
                git commit -m "Removing pin from ${{ inputs.environment }}"
                git push origin main

            - name: Notify Slack of unpinning
              id: slack
              uses: slackapi/slack-github-action@v1.26.0
              with:
                channel-id: 'C10FQV8RE' # ops
                slack-message: "${{ github.actor }} unpinned ${{ inputs.service }} in environment: ${{ inputs.environment }}"
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # TODO: is this in secrets already? if not add it
